name: ci_test
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.9", "3.10"]
      fail-fast: false
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install pdm
    - name: Install project dependencies
      run: pdm install
    - name: Test with pytest
      run: pdm run pytest