name: ci_test
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: sksat/setup-rye@v0.8.0
      - name: install deps
        run: |
          rye sync
      - name: Report test coverage
        run: |
          rye run pytest
