name: run pytest
on: pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: sksat/setup-rye@v0.8.0
      - name: install deps
        run: |
          rye sync --dev
      - name: Report test coverage
        run: |
          rye run pytest --cov-branch --cov-report xml --cov=game tests/ 
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v2
