name: coverage
on: 
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sksat/setup-rye@v0.8.0
      - name: install deps
        run: |
          rye sync
      - name: Report test coverage
        run: |
          rye run pytest --cov-branch --cov-report xml --cov=game tests/ 
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
