name: coverage
on: 
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        # Install latest uv version using the installer
        run: curl -LsSf https://astral.sh/uv/install.sh | sh 
      - name: install python version
        run: |
          uv python install
      - name: install deps
        run: |
          uv sync
      - name: Report test coverage
        run: |
          uv run pytest --cov-branch --cov-report xml --cov=game tests/ 
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
